name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - run: chmod +x ./gradlew
    - run: echo $RELEASE_STORE | base64 --decode > app/keystore.jks
      env:
        RELEASE_STORE: ${{ secrets.RELEASE_STORE }}
    - run: ./gradlew assembleDebug
      env:
        RELEASE_STORE_FILE: keystore.jks
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - run: ./gradlew assembleRelease
      env:
        RELEASE_STORE_FILE: keystore.jks
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
    - uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.md
        files: app/build/outputs/apk/**/*.apk
        draft: true
