name: Release

on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jangrewe/gitlab-ci-androids
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
    - run: |
        export GRADLE_USER_HOME=$(pwd)/.gradle
        chmod +x ./gradlew
        ./gradlew assembleRelease
    - uses: softprops/action-gh-release@v2
      with:
        body_path: RELEASE.md
        files: app/builds/output/apk/**/*.apk
        make_latest: true
